export const FACILITY_KEY_MAP: Record<string, string> = {
  wifi: 'WiFi',
  strong_wifi: 'WiFi',
  power_outlet: 'Power Outlet',
  power_outlets: 'Power Outlet',
  mushola: 'Mushola',
  prayer_room: 'Mushola',
  parking: 'Parking',
  kid_friendly: 'Kid-Friendly',
  quiet_atmosphere: 'Quiet Atmosphere',
  large_tables: 'Large Tables',
  outdoor_area: 'Outdoor Area',
  outdoor_seating: 'Outdoor Area',
  cozy_seating: 'Cozy Seating',
  ambient_lighting: 'Ambient Lighting',
  intimate_seating: 'Intimate Seating',
  noise_tolerant: 'Family Friendly',
  spacious: 'Spacious',
  whiteboard: 'Whiteboard',
  bookable_space: 'Bookable Space',
  smoking_area: 'Smoking Area',
};
